// Decompiled Web Assembly generated by wasmdec. Preamble:
#include <stdint.h> // For the bit size specific types
#include <math.h> // For certian WASM operations
typedef const char* wasm_table_t; // WASM tables
// Bit size specific types not declared in stdint.h:
typedef float float32_t;
typedef double float64_t;
// C implementation of WASM expressions:
unsigned int _rotl(const unsigned int value, int shift) {
	if ((shift &= sizeof(value) * 8 - 1) == 0)
		return value;
	return (value << shift) | (value >> (sizeof(value)*8 - shift));
}
unsigned int _rotr(const unsigned int value, int shift) {
	if ((shift &= sizeof(value) * 8 - 1) == 0)
		return value;
	return (value >> shift) | (value << (sizeof(value)*8 - shift));
}
#define MAX(a,b) ((a) > (b) ? a : b)
#define MIN(a,b) ((a) < (b) ? a : b)
// Host functions: used to request information from host machine.
extern int32_t host_has_feature(int32_t feature_opcode);
extern void host_grow_memory(int32_t size);
extern int32_t host_get_current_memory(void);
extern int32_t host_get_page_size(void);
// End of preamble

// WASM imports:
/*
	Import 'DYNAMICTOP_PTR$asm2wasm$import':
	Module: 'env'
	Base: 'DYNAMICTOP_PTR'
*/
extern int DYNAMICTOP_PTR$asm2wasm$import;
/*
	Import 'tempDoublePtr$asm2wasm$import':
	Module: 'env'
	Base: 'tempDoublePtr'
*/
extern int tempDoublePtr$asm2wasm$import;
/*
	Import 'ABORT$asm2wasm$import':
	Module: 'env'
	Base: 'ABORT'
*/
extern int ABORT$asm2wasm$import;
/*
	Import 'memoryBase':
	Module: 'env'
	Base: 'memoryBase'
*/
extern int memoryBase;
/*
	Import 'tableBase':
	Module: 'env'
	Base: 'tableBase'
*/
extern int tableBase;
/*
	Import 'nan$asm2wasm$import':
	Module: 'global'
	Base: 'NaN'
*/
extern double nan$asm2wasm$import;
/*
	Import 'inf$asm2wasm$import':
	Module: 'global'
	Base: 'Infinity'
*/
extern double inf$asm2wasm$import;
/*
	Import 'abortStackOverflow':
	Module: 'env'
	Base: 'abortStackOverflow'
*/
extern void abortStackOverflow(int local_0)
/*
	Import '_printf':
	Module: 'env'
	Base: '_printf'
*/
extern int _printf(int local_0, int local_1)
/*
	Import '0':
	Module: 'env'
	Base: 'memory'
*/
extern const char* 0; // <Imported memory>
/*
	Import 'import$table$0':
	Module: 'env'
	Base: 'table'
*/
extern wasm_table_t import$table$0; // <Imported table>
// WASM globals:
int DYNAMICTOP_PTR = DYNAMICTOP_PTR$asm2wasm$import;
int tempDoublePtr = tempDoublePtr$asm2wasm$import;
int ABORT = ABORT$asm2wasm$import;
int STACKTOP = 0;
int STACK_MAX = 0;
int __THREW__ = 0;
int threwValue = 0;
int setjmpId = 0;
int undef = 0;
double nan = nan$asm2wasm$import;
double inf = inf$asm2wasm$import;
int tempInt = 0;
int tempBigInt = 0;
int tempBigIntS = 0;
int tempValue = 0;
double tempDouble = 0.000000;
int tempRet0 = 0;
float tempFloat = 0.000000;
float f0 = 0.000000;

// WASM functions:

/*
	Function '$stackAlloc'
	Local variables: 1
	Parameters: 1
*/
int fn_stackAlloc(int local_0) {
	// Parsed WASM function locals:
	int local_1 = 0; // Local with index '1'

	local_1 = STACKTOP;
	STACKTOP = STACKTOP + local_0;
	STACKTOP = STACKTOP + 15 && -16;
	if (STACKTOP >= STACK_MAX) {
	abortStackOverflow(local_0);

	} // <No else block>
	return local_1;
}
/*
	Function '$stackSave'
	Local variables: 0
	Parameters: 0
*/
int fn_stackSave() {
	// Function contains no non-parameter locals
	return STACKTOP;
}
/*
	Function '$stackRestore'
	Local variables: 0
	Parameters: 1
*/
void fn_stackRestore(int local_0) {
	// Function contains no non-parameter locals
	STACKTOP = local_0;
}
/*
	Function '$establishStackSpace'
	Local variables: 0
	Parameters: 2
*/
void fn_establishStackSpace(int local_0, int local_1) {
	// Function contains no non-parameter locals
	STACKTOP = local_0;
	STACK_MAX = local_1;
}
/*
	Function '$setThrew'
	Local variables: 0
	Parameters: 2
*/
void fn_setThrew(int local_0, int local_1) {
	// Function contains no non-parameter locals
	if (__THREW__ == 0) {
	__THREW__ = local_0;
	threwValue = local_1;

	} // <No else block>
}
/*
	Function '$_doubleValue'
	Local variables: 5
	Parameters: 1
*/
int fn__doubleValue(int local_0) {
	// Parsed WASM function locals:
	int local_1 = 0; // Local with index '1'
	int local_2 = 0; // Local with index '2'
	int local_3 = 0; // Local with index '3'
	int local_4 = 0; // Local with index '4'
	int local_5 = 0; // Local with index '5'

	local_5 = STACKTOP;
	STACKTOP = STACKTOP + 16;
	if (STACKTOP >= STACK_MAX) {
	abortStackOverflow(16);

	} // <No else block>
	local_1 = local_0;
	local_2 = local_1;
	local_3 = local_2 << 1;
	STACKTOP = local_5;
	return local_3;
}
/*
	Function '$_main'
	Local variables: 14
	Parameters: 0
*/
int fn__main() {
	// Parsed WASM function locals:
	int local_0 = 0; // Local with index '0'
	int local_1 = 0; // Local with index '1'
	int local_2 = 0; // Local with index '2'
	int local_3 = 0; // Local with index '3'
	int local_4 = 0; // Local with index '4'
	int local_5 = 0; // Local with index '5'
	int local_6 = 0; // Local with index '6'
	int local_7 = 0; // Local with index '7'
	int local_8 = 0; // Local with index '8'
	int local_9 = 0; // Local with index '9'
	int local_10 = 0; // Local with index '10'
	int local_11 = 0; // Local with index '11'
	int local_12 = 0; // Local with index '12'
	int local_13 = 0; // Local with index '13'

	local_13 = STACKTOP;
	STACKTOP = STACKTOP + 32;
	if (STACKTOP >= STACK_MAX) {
	abortStackOverflow(32);

	} // <No else block>
	local_11 = local_13 + 8;
	local_10 = local_13;
	local_0 = 0;
	while (1) { // Loop name: 'while-in'
	local_3 = local_1;
	local_4 = local_3 + 1;
	local_1 = local_4;
	local_5 = local_1;
	local_6 = local_5 < 10;
	if (local_6) {
	break;
	} // <No else block>
	break;
	} // End of loop 'while-in'
	/*  Store:
	Offset: 0x00000000
	Align:  0x00000004
	Bytes:  0x00000004
	Atomic: false  */
	local_10 = memoryBase + 4; 
	/* Drop routine */
	_printf(memoryBase + 0, local_10);
	/* End of drop routine */
	local_1 = 6;
	local_7 = local_1;
	local_8 = 	fn__doubleValue(local_7);
;
	local_2 = local_8;
	local_9 = local_2;
	/*  Store:
	Offset: 0x00000000
	Align:  0x00000004
	Bytes:  0x00000004
	Atomic: false  */
	local_11 = local_9; 
	/* Drop routine */
	_printf(memoryBase + 20, local_11);
	/* End of drop routine */
	STACKTOP = local_13;
	return 0;
}
/*
	Function '$runPostSets'
	Local variables: 1
	Parameters: 0
*/
void fn_runPostSets() {
	// Parsed WASM function locals:
	int local_0 = 0; // Local with index '0'

	// <Nop expression>
}
/*
	Function '$__post_instantiate'
	Local variables: 0
	Parameters: 0
*/
void fn___post_instantiate() {
	// Function contains no non-parameter locals
	STACKTOP = memoryBase + 48;
	STACK_MAX = STACKTOP + 5242880;
	fn_runPostSets();
}

/*
	Exported WASM functions:
	Function 'fn__main':
		WASM name: '_main'
		Export name: '_main'

	Function 'fn___post_instantiate':
		WASM name: '__post_instantiate'
		Export name: '__post_instantiate'

	Function 'fn_runPostSets':
		WASM name: 'runPostSets'
		Export name: 'runPostSets'

	Function 'fn__doubleValue':
		WASM name: '_doubleValue'
		Export name: '_doubleValue'

*/
