// Decompiled Web Assembly generated by wdis
// Preamble:
#include <stdint.h>
typedef float float32_t;
typedef double float64_t;

// WASM imports:
// WASM functions:
int32_t fn_0(int32_t arg0, int32_t arg1) {
	return arg0 + arg1;
}