// Decompiled Web Assembly generated by wdis
// Preamble:
#include <stdint.h>
#include <math.h>
typedef float float32_t;
typedef double float64_t;

// No WASM imports

// WASM functions:
int32_t fn_0(int32_t arg0, int32_t arg1) {
	return local_0 + local_1;
}void fn_1() {
	1return;
}