// Decompiled Web Assembly generated by wdis
// Preamble:
#include <stdint.h>
#include <math.h>
typedef float float32_t;
typedef double float64_t;

// No WASM imports

// WASM functions:
int32_t fn_0(int32_t local_0, int32_t local_1) {
	return local_0 + local_1;
}
int32_t fn_1() {
	return 1;
}
