// Decompiled Web Assembly generated by wasmdec. Preamble:
#include <stdint.h> // For the bit size specific types
#include <math.h> // For certian WASM binary operations
typedef const char* wasm_table_t; // WASM tables
// Bit size specific types not declared in stdint.h:
typedef float float32_t;
typedef double float64_t;
// End of preamble

// No WASM imports.

// No WASM globals.

// WASM functions:

/*
	Function '$0'
	Local variables: 0
	Parameters: 2
	Immediate block expressions: 1
*/
int32_t fn_0(int32_t local_0, int32_t local_1) {
	// Function contains no non-parameter locals
	return local_0 + local_1;
}

/*
	Exported WASM functions:
	Function 'fn_0':
		WASM name: '0'
		Export name: 'addTwo'

*/
