// Decompiled Web Assembly generated by wdis. Preamble:
#include <stdint.h> // For the bit size specific types
#include <math.h> // For certian WASM binary operations
typedef const char* wasm_table_t; // WASM tables
// Bit size specific types not declared in stdint.h:
typedef float float32_t;
typedef double float64_t;
// End of preamble

// WASM imports:
/*
	Import 'import$0':
	Module: 'env'
	Base: 'DYNAMICTOP_PTR'
*/
extern int32_t import$0;
/*
	Import 'import$1':
	Module: 'env'
	Base: 'tempDoublePtr'
*/
extern int32_t import$1;
/*
	Import 'import$2':
	Module: 'env'
	Base: 'ABORT'
*/
extern int32_t import$2;
/*
	Import 'import$3':
	Module: 'env'
	Base: 'memoryBase'
*/
extern int32_t import$3;
/*
	Import 'import$4':
	Module: 'env'
	Base: 'tableBase'
*/
extern int32_t import$4;
/*
	Import 'import$5':
	Module: 'global'
	Base: 'NaN'
*/
extern float64_t import$5;
/*
	Import 'import$6':
	Module: 'global'
	Base: 'Infinity'
*/
extern float64_t import$6;
/*
	Import 'import$7':
	Module: 'env'
	Base: 'abortStackOverflow'
*/
extern void import$7(int32_t local_0)
/*
	Import 'import$8':
	Module: 'env'
	Base: 'memory'
*/
extern const char* import$8; // <Imported memory>
/*
	Import 'import$9':
	Module: 'env'
	Base: 'table'
*/
extern wasm_table_t import$9; // <Imported table>
// WASM functions:

/*
	Function '$stackAlloc'
	Local variables: 1
	Parameters: 1
	Immediate block expressions: 1
*/
int32_t fn_stackAlloc(int32_t local_0) {
	// Parsed WASM function locals:
	int32_t local_1 = 0; // Local with index '1'

	local_1 = global$3;
	global$3 = global$3 + local_0;
	global$3 = global$3 + 15 && -16;
	if (global$3 >= global$4) {
		/* Import call */ import$7(local_0)
	} // <No else block>
	return local_1;
}
/*
	Function '$stackSave'
	Local variables: 0
	Parameters: 0
	Immediate block expressions: 1
*/
int32_t fn_stackSave() {
	// Function contains no non-parameter locals
return global$3;
}
/*
	Function '$stackRestore'
	Local variables: 0
	Parameters: 1
	Immediate block expressions: 1
*/
void fn_stackRestore(int32_t local_0) {
	// Function contains no non-parameter locals
global$3 = local_0;
}
/*
	Function '$establishStackSpace'
	Local variables: 0
	Parameters: 2
	Immediate block expressions: 1
*/
void fn_establishStackSpace(int32_t local_0, int32_t local_1) {
	// Function contains no non-parameter locals
	global$3 = local_0;
	global$4 = local_1;
}
/*
	Function '$setThrew'
	Local variables: 0
	Parameters: 2
	Immediate block expressions: 1
*/
void fn_setThrew(int32_t local_0, int32_t local_1) {
	// Function contains no non-parameter locals
if (global$5 == 0) {
		global$5 = local_0;
	global$6 = local_1;

} // <No else block>
}
/*
	Function '$_main'
	Local variables: 3
	Parameters: 0
	Immediate block expressions: 1
*/
int32_t fn__main() {
	// Parsed WASM function locals:
	int32_t local_0 = 0; // Local with index '0'
	int32_t local_1 = 0; // Local with index '1'
	int32_t local_2 = 0; // Local with index '2'

	local_2 = global$3;
	global$3 = global$3 + 16;
	if (global$3 >= global$4) {
		/* Import call */ import$7(16)
	} // <No else block>
	local_0 = 0;
	global$3 = local_2;
	return 0;
}
/*
	Function '$runPostSets'
	Local variables: 1
	Parameters: 0
	Immediate block expressions: 1
*/
void fn_runPostSets() {
	// Parsed WASM function locals:
	int32_t local_0 = 0; // Local with index '0'

// <Nop expression>
}
/*
	Function '$__post_instantiate'
	Local variables: 0
	Parameters: 0
	Immediate block expressions: 1
*/
void fn___post_instantiate() {
	// Function contains no non-parameter locals
	global$3 = import$3 + 0;
	global$4 = global$3 + 5242880;
fn_runPostSets()}

/*
	Exported WASM functions:
	Function 'fn___post_instantiate':
		WASM name: '__post_instantiate'
		Export name: '__post_instantiate'

	Function 'fn__main':
		WASM name: '_main'
		Export name: '_main'

	Function 'fn_runPostSets':
		WASM name: 'runPostSets'
		Export name: 'runPostSets'

*/
