#ifndef _WDIS_EMITTER_H
#define _WDIS_EMITTER_H

#include <fstream>
#include <sstream>
#include <vector>
#include <string>
#include <iostream>
#include <iterator>
using namespace std;

namespace wdis {
	class Emitter {
	public:
		Emitter() {
			// Preamble
			str << "// Decompiled Web Assembly generated by wdis. Preamble:" << endl
			<< "#include <stdint.h> // For the bit size specific types" << endl
			<< "#include <math.h> // For certian WASM binary operations" << endl
			<< "// Bit size specific types not declared in stdint.h:" << endl
			<< "typedef float float32_t;" << endl
			<< "typedef double float64_t;" << endl
			<< "// End of preamble" << endl << endl;
		}
		stringstream& operator<<(string out) {
			str << out;
			return str;
		}
		void comment(string cmt) {
			str << "// " << cmt << endl;
		}
		void ln() {
			str << endl;
		}
		string getCode() {
			return str.str();
		}
	protected:
		stringstream str;
	};
} // namespace wdis

#endif // _WDIS_EMITTER_H