#include "Emitter.h"
using namespace wdis;
using namespace std;

Emitter::Emitter() {
	// Preamble
	str << "// Decompiled Web Assembly generated by wdis. Preamble:" << endl
	<< "#include <stdint.h> // For the bit size specific types" << endl
	<< "#include <math.h> // For certian WASM binary operations" << endl
	<< "typedef const char* wasm_table_t; // WASM tables" << endl
	<< "// Bit size specific types not declared in stdint.h:" << endl
	<< "typedef float float32_t;" << endl
	<< "typedef double float64_t;" << endl
	<< "// End of preamble" << endl << endl;
}
stringstream& Emitter::operator<<(string out) {
	str << out;
	return str;
}
void Emitter::comment(string cmt) {
	str << "// " << cmt << endl;
}
void Emitter::ln() {
	str << endl;
}
string Emitter::getCode() {
	return str.str();
}